### ISSUE TITLE
请教一下 half edge collapse 的算法问题

### ISSUE THREAD

**Issue by airycanon** [lihy96/MeshSimplify#1]
你好，最近在学习 half edge 合并和删除顶点的理论知识，准备用 Rust 实现出来，对 half edge 的算法都是从一些国外的文献了解到的，并不深入，恰好碰到你的项目，方便的话，可否推荐一些这方面的资料，不当之处请见谅，谢谢。

**Comment by lihy96** [comment]
你好，很高兴收到你的邮件。

我基本上是按照一篇paper上提供的算法实现的（README.md中参考文献的第一个，可以谷歌也可以百度到），感觉效果不错，可以看看是否符合你的需求。

我是用c++写的，对Rust实在了解甚少，深表歉意。

**Comment by airycanon** [comment]
多谢，我去看看，再结合你的代码学习一下，如果有不明白的地方，希望还可以跟你请教。
